<?php

namespace AppBundle\Repository;

/**
 * pedidoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class pedidoRepository extends \Doctrine\ORM\EntityRepository
{
}
